<a href="https://colab.research.google.com/github/Ethic41/deep_learning/blob/master/pytorch/60_min_blitz_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [4]:
x_np

tensor([[1, 2],
        [3, 4]])

In [5]:
x_ones = torch.ones_like(x_data)

In [6]:
x_ones

tensor([[1, 1],
        [1, 1]])

In [7]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
x_rand

tensor([[0.2934, 0.9435],
        [0.8162, 0.6458]])

In [8]:
shape = (2, 3, )
rand_tensor = torch.rand(shape)
rand_tensor

tensor([[0.1606, 0.8202, 0.9570],
        [0.0299, 0.5038, 0.2680]])

In [9]:
ones_tensor = torch.ones(shape)
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
zeros_tensor = torch.zeros(shape)
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
tensor = torch.rand(3, 4)

In [12]:
tensor

tensor([[0.9275, 0.2898, 0.9390, 0.9949],
        [0.5318, 0.1517, 0.5107, 0.7115],
        [0.4489, 0.2844, 0.3477, 0.2262]])

In [13]:
print(f"Shape of tensor {tensor.shape}")

Shape of tensor torch.Size([3, 4])


In [14]:
print(f"Datatype of tensor: {tensor.dtype}")

Datatype of tensor: torch.float32


In [15]:
print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cpu


In [16]:
tensor = torch.ones(4, 4)
print(f"{tensor}")

tensor[:, 1] = 0
print(f"{tensor}")



tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [19]:
t1 = torch.cat([tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.]])


In [20]:
tensor * tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [21]:
tensor.mul(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [22]:
tensor.matmul(tensor.T)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [23]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [24]:
tensor.T

tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
tensor.T

tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
tensor.T

tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
tensor.T.T

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [28]:
tensor @ tensor

tensor([[3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.]])

In [29]:
tensor + 5

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

In [30]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [31]:
tensor.add(5)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

In [32]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [33]:
tensor1 = tensor

In [34]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [35]:
tensor1

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [36]:
tensor1.add_(5)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

In [37]:
tensor1

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

In [38]:
tensor2 = torch.rand(1, 3, 64, 64)

In [39]:
tensor2 

tensor([[[[0.0318, 0.1571, 0.8849,  ..., 0.6004, 0.8022, 0.5094],
          [0.7851, 0.2291, 0.6493,  ..., 0.6302, 0.8993, 0.0085],
          [0.8131, 0.2228, 0.4054,  ..., 0.6595, 0.9104, 0.9151],
          ...,
          [0.8599, 0.3521, 0.7266,  ..., 0.0590, 0.1908, 0.4004],
          [0.1627, 0.7538, 0.0101,  ..., 0.5277, 0.2775, 0.6883],
          [0.3791, 0.6081, 0.4120,  ..., 0.9782, 0.0563, 0.7062]],

         [[0.0528, 0.3393, 0.8383,  ..., 0.0367, 0.8828, 0.7563],
          [0.1582, 0.6316, 0.7010,  ..., 0.8287, 0.4746, 0.8760],
          [0.5761, 0.5501, 0.5448,  ..., 0.1259, 0.8055, 0.1602],
          ...,
          [0.0467, 0.4550, 0.3363,  ..., 0.6850, 0.3843, 0.0481],
          [0.8691, 0.8662, 0.3526,  ..., 0.9290, 0.9479, 0.2451],
          [0.9924, 0.5069, 0.9089,  ..., 0.3524, 0.4452, 0.8147]],

         [[0.1942, 0.5891, 0.8665,  ..., 0.1084, 0.4731, 0.0444],
          [0.9750, 0.8340, 0.0500,  ..., 0.1404, 0.1844, 0.0407],
          [0.4633, 0.4025, 0.6107,  ..., 0

In [43]:
for t in tensor2[0]:
  print(f">>>> tensor: {t}")
  print(f">>>> tensor shape: {t.shape}")

>>>> tensor: tensor([[0.0318, 0.1571, 0.8849,  ..., 0.6004, 0.8022, 0.5094],
        [0.7851, 0.2291, 0.6493,  ..., 0.6302, 0.8993, 0.0085],
        [0.8131, 0.2228, 0.4054,  ..., 0.6595, 0.9104, 0.9151],
        ...,
        [0.8599, 0.3521, 0.7266,  ..., 0.0590, 0.1908, 0.4004],
        [0.1627, 0.7538, 0.0101,  ..., 0.5277, 0.2775, 0.6883],
        [0.3791, 0.6081, 0.4120,  ..., 0.9782, 0.0563, 0.7062]])
>>>> tensor shape: torch.Size([64, 64])
>>>> tensor: tensor([[0.0528, 0.3393, 0.8383,  ..., 0.0367, 0.8828, 0.7563],
        [0.1582, 0.6316, 0.7010,  ..., 0.8287, 0.4746, 0.8760],
        [0.5761, 0.5501, 0.5448,  ..., 0.1259, 0.8055, 0.1602],
        ...,
        [0.0467, 0.4550, 0.3363,  ..., 0.6850, 0.3843, 0.0481],
        [0.8691, 0.8662, 0.3526,  ..., 0.9290, 0.9479, 0.2451],
        [0.9924, 0.5069, 0.9089,  ..., 0.3524, 0.4452, 0.8147]])
>>>> tensor shape: torch.Size([64, 64])
>>>> tensor: tensor([[0.1942, 0.5891, 0.8665,  ..., 0.1084, 0.4731, 0.0444],
        [0.9750, 0.83

In [44]:
tensor3 = torch.rand(1, 1000)

In [46]:
tensor3.shape

torch.Size([1, 1000])

In [47]:
tensor3

tensor([[6.7554e-01, 8.3782e-01, 1.6278e-01, 8.0880e-01, 3.6566e-01, 4.6663e-01,
         5.3005e-01, 6.9341e-01, 1.9535e-01, 1.5311e-01, 4.5928e-01, 7.8130e-01,
         8.2457e-01, 9.6818e-01, 2.9547e-01, 4.9612e-01, 8.3221e-01, 6.9866e-01,
         5.7300e-01, 3.7635e-01, 2.3624e-01, 3.8964e-01, 9.7494e-01, 8.0412e-01,
         7.4995e-01, 9.2712e-01, 8.8770e-01, 7.7403e-02, 4.4619e-01, 2.2726e-01,
         9.2739e-01, 1.5838e-01, 8.9205e-01, 8.6778e-01, 3.6293e-01, 1.1809e-01,
         3.2616e-02, 4.8840e-01, 7.8555e-01, 5.3586e-01, 7.9630e-01, 3.0649e-01,
         6.9161e-01, 2.5736e-01, 9.4796e-01, 8.3652e-01, 5.9352e-01, 7.9181e-01,
         3.8324e-01, 4.4098e-01, 9.7393e-02, 3.7116e-01, 9.6298e-01, 8.1032e-01,
         9.5252e-01, 6.2344e-01, 9.7866e-01, 7.8001e-01, 9.1181e-01, 8.6039e-02,
         9.3752e-01, 2.7642e-01, 2.6089e-02, 2.7956e-01, 7.7622e-01, 6.6169e-01,
         9.7863e-02, 3.0835e-01, 2.9519e-02, 7.8540e-01, 4.1605e-01, 2.3037e-01,
         2.8430e-01, 8.4233e