<a href="https://colab.research.google.com/github/Ethic41/deep_learning/blob/master/pytorch/neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms



In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"using {device} device")

using cuda device


In [3]:
class NeuralNetwork(nn.Module):
  def __init__(self):
    super(NeuralNetwork, self).__init__()
    self.flatten = nn.Flatten()
    self.linear_relu_stack = nn.Sequential(
        nn.Linear(28*28, 512),
        nn.ReLU(),
        nn.Linear(512, 512),
        nn.ReLU(),
        nn.Linear(512, 10),
        nn.ReLU()
    )
  
  def forward(self, x):
    x = self.flatten(x)
    logits = self.linear_relu_stack(x)
    return logits



In [4]:
model = NeuralNetwork().to(device)

In [5]:
X = torch.rand(1, 28, 28, device=device)
logits = model(X)
pred_probab = nn.Softmax(dim=1)(logits)
y_pred = pred_probab.argmax(1)
print(f"Predicted class: {y_pred}")

Predicted class: tensor([5], device='cuda:0')


In [6]:
input_image = torch.rand(3, 28, 28)
print(input_image.size())

torch.Size([3, 28, 28])


In [7]:
input_image

tensor([[[0.8338, 0.4421, 0.9767,  ..., 0.5505, 0.5362, 0.3428],
         [0.4752, 0.3561, 0.4641,  ..., 0.4480, 0.6064, 0.1242],
         [0.5081, 0.8368, 0.3090,  ..., 0.2357, 0.9312, 0.5381],
         ...,
         [0.1717, 0.4560, 0.0960,  ..., 0.4245, 0.0739, 0.2715],
         [0.6873, 0.5924, 0.3658,  ..., 0.3414, 0.5221, 0.1075],
         [0.7742, 0.6632, 0.6535,  ..., 0.5806, 0.6136, 0.6844]],

        [[0.4626, 0.4872, 0.4747,  ..., 0.9995, 0.1516, 0.2835],
         [0.8786, 0.1196, 0.7424,  ..., 0.0470, 0.6741, 0.5461],
         [0.6710, 0.0028, 0.9920,  ..., 0.6967, 0.9387, 0.0714],
         ...,
         [0.4740, 0.5679, 0.4441,  ..., 0.9790, 0.7698, 0.0326],
         [0.5798, 0.4806, 0.5331,  ..., 0.0499, 0.0971, 0.6356],
         [0.0847, 0.6660, 0.4154,  ..., 0.9437, 0.8981, 0.9853]],

        [[0.1166, 0.7669, 0.2135,  ..., 0.8266, 0.0279, 0.2952],
         [0.0287, 0.0683, 0.8518,  ..., 0.0986, 0.4582, 0.0550],
         [0.7444, 0.0850, 0.2803,  ..., 0.9478, 0.7738, 0.

In [8]:
flatten = nn.Flatten()
flat_image = flatten(input_image)
print(flat_image.size())

torch.Size([3, 784])


In [9]:
flat_image

tensor([[0.8338, 0.4421, 0.9767,  ..., 0.5806, 0.6136, 0.6844],
        [0.4626, 0.4872, 0.4747,  ..., 0.9437, 0.8981, 0.9853],
        [0.1166, 0.7669, 0.2135,  ..., 0.7804, 0.6509, 0.9506]])

In [11]:
layer1 = nn.Linear(in_features=28*28, out_features=20)
hidden1 = layer1(flat_image)
print(hidden1.size())

torch.Size([3, 20])


In [12]:
hidden1

tensor([[-0.0373,  0.3182, -0.0409,  0.6543, -0.1539,  0.3342,  0.4465,  0.3082,
         -0.0221,  0.0855,  0.4120, -0.3282, -0.1658,  0.3449,  0.3416,  0.0084,
         -0.1874,  0.4792,  0.0365, -0.1241],
        [ 0.1962,  0.3512,  0.1472,  0.4314,  0.2013,  0.2971,  0.7332,  0.2000,
         -0.0489,  0.0610,  0.4259, -0.0464, -0.4247,  0.4220,  0.4808,  0.5562,
         -0.5074,  0.0806,  0.2490,  0.1139],
        [-0.4013,  0.2450,  0.2255,  0.7021, -0.0812, -0.3193,  0.5473,  0.1059,
          0.1038, -0.2793,  0.2983, -0.3292, -0.1629,  0.0268,  0.3487,  0.1554,
         -0.2208,  0.0709,  0.0076, -0.1576]], grad_fn=<AddmmBackward>)

In [13]:
print(f"Before ReLU: {hidden1}\n\n")
hidden1 = nn.ReLU()(hidden1)
print(f"After ReLU: {hidden1}")

Before ReLU: tensor([[-0.0373,  0.3182, -0.0409,  0.6543, -0.1539,  0.3342,  0.4465,  0.3082,
         -0.0221,  0.0855,  0.4120, -0.3282, -0.1658,  0.3449,  0.3416,  0.0084,
         -0.1874,  0.4792,  0.0365, -0.1241],
        [ 0.1962,  0.3512,  0.1472,  0.4314,  0.2013,  0.2971,  0.7332,  0.2000,
         -0.0489,  0.0610,  0.4259, -0.0464, -0.4247,  0.4220,  0.4808,  0.5562,
         -0.5074,  0.0806,  0.2490,  0.1139],
        [-0.4013,  0.2450,  0.2255,  0.7021, -0.0812, -0.3193,  0.5473,  0.1059,
          0.1038, -0.2793,  0.2983, -0.3292, -0.1629,  0.0268,  0.3487,  0.1554,
         -0.2208,  0.0709,  0.0076, -0.1576]], grad_fn=<AddmmBackward>)


After ReLU: tensor([[0.0000, 0.3182, 0.0000, 0.6543, 0.0000, 0.3342, 0.4465, 0.3082, 0.0000,
         0.0855, 0.4120, 0.0000, 0.0000, 0.3449, 0.3416, 0.0084, 0.0000, 0.4792,
         0.0365, 0.0000],
        [0.1962, 0.3512, 0.1472, 0.4314, 0.2013, 0.2971, 0.7332, 0.2000, 0.0000,
         0.0610, 0.4259, 0.0000, 0.0000, 0.4220, 0.480

In [16]:
seq_modules = nn.Sequential(
    flatten,
    layer1,
    nn.ReLU(),
    nn.Linear(20, 10)
)

input_image = torch.rand(3, 28, 28)
logits = seq_modules(input_image)


In [18]:
softmax = nn.Softmax(dim=1)
pred_probab = softmax(logits)

In [19]:
pred_probab

tensor([[0.1042, 0.0969, 0.0755, 0.1169, 0.0878, 0.1000, 0.1405, 0.1038, 0.0845,
         0.0899],
        [0.0928, 0.1035, 0.0728, 0.1209, 0.0893, 0.0980, 0.1476, 0.1050, 0.0820,
         0.0879],
        [0.0928, 0.1003, 0.0758, 0.1367, 0.0862, 0.0898, 0.1432, 0.0958, 0.0804,
         0.0991]], grad_fn=<SoftmaxBackward>)

In [20]:
pred_probab * (100)

tensor([[10.4164,  9.6882,  7.5520, 11.6944,  8.7771, 10.0050, 14.0488, 10.3756,
          8.4532,  8.9893],
        [ 9.2834, 10.3519,  7.2827, 12.0947,  8.9263,  9.8047, 14.7623, 10.5038,
          8.2007,  8.7894],
        [ 9.2752, 10.0269,  7.5813, 13.6691,  8.6199,  8.9791, 14.3240,  9.5814,
          8.0353,  9.9078]], grad_fn=<MulBackward0>)

In [22]:
pred_probab

tensor([[0.1042, 0.0969, 0.0755, 0.1169, 0.0878, 0.1000, 0.1405, 0.1038, 0.0845,
         0.0899],
        [0.0928, 0.1035, 0.0728, 0.1209, 0.0893, 0.0980, 0.1476, 0.1050, 0.0820,
         0.0879],
        [0.0928, 0.1003, 0.0758, 0.1367, 0.0862, 0.0898, 0.1432, 0.0958, 0.0804,
         0.0991]], grad_fn=<SoftmaxBackward>)

In [23]:
logits

tensor([[ 0.0594, -0.0130, -0.2621,  0.1752, -0.1118,  0.0191,  0.3586,  0.0555,
         -0.1494, -0.0879],
        [-0.0441,  0.0649, -0.2868,  0.2205, -0.0833,  0.0106,  0.4198,  0.0794,
         -0.1681, -0.0988],
        [-0.0596,  0.0183, -0.2612,  0.3282, -0.1329, -0.0920,  0.3750, -0.0271,
         -0.2031,  0.0064]], grad_fn=<AddmmBackward>)

In [24]:
print(f"Model structure: {model} \n\n")

Model structure: NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
    (5): ReLU()
  )
) 




In [27]:
for name, param in model.named_parameters():
  print(f"Layer: {name} | \n Size: {param.size()} | \n Values: {param[:2]} \n")

Layer: linear_relu_stack.0.weight | 
 Size: torch.Size([512, 784]) | 
 Values: tensor([[-0.0348, -0.0194,  0.0152,  ...,  0.0206, -0.0316, -0.0035],
        [-0.0167, -0.0229, -0.0202,  ...,  0.0225, -0.0014,  0.0317]],
       device='cuda:0', grad_fn=<SliceBackward>) 

Layer: linear_relu_stack.0.bias | 
 Size: torch.Size([512]) | 
 Values: tensor([-0.0281, -0.0232], device='cuda:0', grad_fn=<SliceBackward>) 

Layer: linear_relu_stack.2.weight | 
 Size: torch.Size([512, 512]) | 
 Values: tensor([[ 0.0106,  0.0160,  0.0121,  ..., -0.0176,  0.0317, -0.0435],
        [-0.0372,  0.0243, -0.0362,  ..., -0.0041,  0.0259,  0.0441]],
       device='cuda:0', grad_fn=<SliceBackward>) 

Layer: linear_relu_stack.2.bias | 
 Size: torch.Size([512]) | 
 Values: tensor([ 0.0166, -0.0034], device='cuda:0', grad_fn=<SliceBackward>) 

Layer: linear_relu_stack.4.weight | 
 Size: torch.Size([10, 512]) | 
 Values: tensor([[-0.0383, -0.0361, -0.0064,  ...,  0.0056, -0.0363, -0.0042],
        [ 0.0134,  0.009