<a href="https://colab.research.google.com/github/Ethic41/deep_learning/blob/master/pytorch/pytorch_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [ ]:
x_data

tensor([[1, 2],
        [3, 4]])

In [ ]:
np_array = np.array(data)

In [ ]:
np_array

array([[1, 2],
       [3, 4]])

In [ ]:
type(np_array)

numpy.ndarray

In [ ]:
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [ ]:
x_ones = torch.ones_like(x_data)

In [ ]:
x_ones

tensor([[1, 1],
        [1, 1]])

In [ ]:
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.0107, 0.6765],
        [0.7632, 0.6836]]) 



In [ ]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")


Random Tensor: 
 tensor([[0.1435, 0.3513, 0.7150],
        [0.6074, 0.6299, 0.9223]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [ ]:
tensor = torch.rand(3, 4)

print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


In [ ]:
tensor = torch.ones(4, 4)
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
tensor[0]

tensor([1., 1., 1., 1.])

In [ ]:
tensor[:, 0]

tensor([1., 1., 1., 1.])

In [ ]:
tensor[..., -1]

tensor([1., 1., 1., 1.])

In [ ]:
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
tensor[:, 1] = 0

In [ ]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [ ]:
tensor[:, 2] = 3

In [ ]:
tensor

tensor([[1., 0., 3., 1.],
        [1., 0., 3., 1.],
        [1., 0., 3., 1.],
        [1., 0., 3., 1.]])

In [ ]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
t1

tensor([[1., 0., 3., 1., 1., 0., 3., 1., 1., 0., 3., 1.],
        [1., 0., 3., 1., 1., 0., 3., 1., 1., 0., 3., 1.],
        [1., 0., 3., 1., 1., 0., 3., 1., 1., 0., 3., 1.],
        [1., 0., 3., 1., 1., 0., 3., 1., 1., 0., 3., 1.]])

In [ ]:
y1 = tensor @ tensor.T
y1

tensor([[11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [11., 11., 11., 11.]])

In [ ]:
y2 = tensor.matmul(tensor.T)
y2

tensor([[11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [11., 11., 11., 11.]])

In [ ]:
y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [11., 11., 11., 11.]])

In [ ]:
y3

tensor([[11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [11., 11., 11., 11.]])

In [ ]:
tensor

tensor([[1., 0., 3., 1.],
        [1., 0., 3., 1.],
        [1., 0., 3., 1.],
        [1., 0., 3., 1.]])

In [ ]:
tensor.T

tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [3., 3., 3., 3.],
        [1., 1., 1., 1.]])

In [ ]:
z1 = tensor * tensor
z1

tensor([[1., 0., 9., 1.],
        [1., 0., 9., 1.],
        [1., 0., 9., 1.],
        [1., 0., 9., 1.]])

In [ ]:
z2 = tensor.mul(tensor)
z2

tensor([[1., 0., 9., 1.],
        [1., 0., 9., 1.],
        [1., 0., 9., 1.],
        [1., 0., 9., 1.]])

In [ ]:
z3 = torch.rand_like(tensor)
z3

tensor([[0.5975, 0.3182, 0.9098, 0.8205],
        [0.9537, 0.8197, 0.8302, 0.1345],
        [0.3695, 0.2362, 0.2228, 0.1243],
        [0.6385, 0.3181, 0.6273, 0.5408]])

In [ ]:
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 9., 1.],
        [1., 0., 9., 1.],
        [1., 0., 9., 1.],
        [1., 0., 9., 1.]])

In [ ]:
agg = tensor.sum()
agg

tensor(20.)

In [ ]:
agg_item = agg.item()

In [ ]:
agg_item

20.0

In [ ]:
type(agg_item)

float

In [ ]:
print(tensor)

tensor([[1., 0., 3., 1.],
        [1., 0., 3., 1.],
        [1., 0., 3., 1.],
        [1., 0., 3., 1.]])


In [ ]:
tensor.add_(5)

tensor([[6., 5., 8., 6.],
        [6., 5., 8., 6.],
        [6., 5., 8., 6.],
        [6., 5., 8., 6.]])

In [ ]:
t = torch.ones(5)

In [ ]:
t

tensor([1., 1., 1., 1., 1.])

In [ ]:
n = t.numpy()

In [ ]:
n

array([1., 1., 1., 1., 1.], dtype=float32)

In [ ]:
t.add_(1)

tensor([2., 2., 2., 2., 2.])

In [ ]:
n

array([2., 2., 2., 2., 2.], dtype=float32)

In [ ]:
n = np.ones(5)
n

array([1., 1., 1., 1., 1.])

In [ ]:
t = torch.from_numpy(n)

In [ ]:
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [ ]:
np.add(n, 1, out=n)

array([2., 2., 2., 2., 2.])

In [ ]:
t

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)